# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
# platform :ios, '9.0'

target 'AlicomFusionAuthDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'
  pod 'CYLTabBarController'
  pod 'MBProgressHUD'
  # Pods for AlicomFusionAuthDemo

  target 'AlicomFusionAuthDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlicomFusionAuthDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
